namespace CrowdControl.Games.Packs.MCCCursedHaloCE.Effects
{
    public enum OneShotEffect
    {
        KillPlayer = 1,

        //CrashGame = 2,
        //ResetCheckpoint= 3,
        RestartLevel = 4,

        GiveAllVehicles = 5,

        //ActiveCamo = 6,
        //GiveWeapons = 7,
        SkipLevel = 8,

        //DestroyEverything = 9,
        DisableCrosshair = 10,

        Malfunction = 11,
        RepairHud = 14,
        GiveSafeCheckpoint = 15,
        GiveUnsafeCheckpoint = 16,
        SummonDave = 17,
        SummonMinecraft = 18,
        SummonHunter = 19,
        SummonTurret = 20,
        SummonJohnson = 21,
        SummonPiss = 22,
        SummonSteve = 23,
        AiDoubleUp = 24,
        AiFriendly = 25,
        AiFoe = 26,
        AiShrink = 27,
        AiScream = 28,
        Boing = 29,
        RandomLoadout = 30,
        ActiveCamo = 31,
        SpawnD20 = 32,
        SpawnBlackHole = 33,
        SpawnRandomVehicle = 34,
        SpawnNuke = 35,
        SpawnToolgun = 36,
        UnlockCursedJump = 37,
        UnlockCursedBarrage = 38,
        InfiniteAmmo = 39, // No infinite clips though. I'll keep my implementation.
        MoonGravity = 40,
        Rapture = 41,
        Joyride = 42,
        ForcedDance = 43,
        ArmorLock = 44,
        ForceReversePistol = 45,
        Berserk = 46,
        NoCursedPowerupsCooldown = 47,
        StormyNight_FadeOut = 48,
        StormyNight_FadeIn = 49,
        Paranoia_Start = 50,
        Paranoia_End = 53,
        Flashlight_On = 51,
        Flashlight_Off = 52,
        FlappySpartan_Start = 54,
        FlappySpartan_End = 55,
        SummonCaptain = 56,
        SpawnRat = 57,
        FlappySpartan_Update = 58,

        //----------Sounds
        OneHp = 1000,

        DoubleUp = 1001,
        Fullestauto = 1002,
        Give = 1003,
        Heal = 1004,
        HealingBullets = 1005,
        HeavenOrHell = 1006,
        MalfunctionSound = 1007,
        QuadDamage = 1008,
        RepairHudSound = 1009,
        Yoink = 1010,
        Fullestauto_Stop = 1011,
        Berserker_start = 1012,
        Berserker_stop = 1013,
        Crickets = 1014,
        BodySnatcherS = 1015,
        DeathlessS = 1016,
        EnemyGodModeS = 1017,
        FriendlyS = 1018,
        GlassCannonS = 1019,
        GodModeS = 1020,
        HighGravityS = 1021,
        JetpackS = 1022,
        LowGravityS = 1023,
        MedusaS = 1024,
        NerWarS = 1025,
        OneShotOneKillS = 1026,
        PublicEnemyS = 1027,
        SuperJumpS = 1028,
        UnlimitedAmmoS = 1029,
        SickBeatsS = 1030,
    }
}